### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [angus-lherrou/bureau-env#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by angus-lherrou** [comment]
Hi @unixorn --

Thanks for letting me know! I'm a bit new at licensing--since I modified this from the Bureau theme from the https://github.com/ohmyzsh/ohmyzsh/ repository, should I just copy that MIT license file here, with the original copyright message (`Copyright (c) 2009-2020 Robby Russell and contributors (https://github.com/ohmyzsh/ohmyzsh/contributors)`)?

**Comment by unixorn** [comment]
Yeah, if upstream is MIT, then you should use MIT.

**Comment by angus-lherrou** [comment]
All set, thanks for taking note of my repo! @unixorn
